pipeline {
    agent any
    environment {
        IMAGE_TAG = 'latest'
        ECR_REGISTRY = '639887159307.dkr.ecr.us-east-1.amazonaws.com/github-wrapper'
        AWS_REGION = 'us-east-1'
    }
    stages {
        stage('Test') {
            steps {
                echo 'Running tests...'
                sh './gradlew test'
            }
        }
        stage('Build Docker Image') {
            when {
                expression { params.PUSH_TO_ECR == 'true' }
            }
            steps {
                script {
                    docker.build("${ECR_REGISTRY}:${IMAGE_TAG}")
                }
            }
        }
        stage('Push to ECR') {
            when {
                expression { params.PUSH_TO_ECR == 'true' }
            }
            steps {
                script {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
                        sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY'
                        sh 'docker push $ECR_REGISTRY:$IMAGE_TAG'
                    }
                }
            }
        }
    }
    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'The tag of the Docker image.')
        choice(name: 'PUSH_TO_ECR', choices: ['true', 'false'], description: 'Push built image to ECR')
    }
}